# values.yaml
workloads:
  deployments:
    gameserver:
      enabled: false
      replicas: 1
      image:
        repository: dudgh614/gameserver-app
        tag: "latest"
        pullPolicy: IfNotPresent
      containerPort: 8080

      envFrom:
        - secretRef:
            name: gameserver-app-secrets
      service:
        enabled: false
        type: ClusterIP
        port: 8080
        targetPort: 8080

            
    frontend:
      enabled: false
      image:
        repository: nginx
        tag: "1.27-alpine"
        pullPolicy: IfNotPresent
        
      containerPort: 80
      service:
        enabled: false
        type: ClusterIP
        port: 80
        targetPort: 80
  
  statefulset:
    postgres:
      enabled: false
      replicas: 1
      image:
        repository: postgres
        tag: "latest"
        pullPolicy: IfNotPresent
      containerPort: 5432
      